#!/bin/sh -f

for f in AD.ss QobiScheme.ss deterministic-memoization.ss games.ss lazy-stochastic-montague-grammar.ss  nondeterministic-constraints.ss nondeterministic-memoization.ss nondeterministic-promises.ss nondeterministic-recognizer.ss nondeterministic-scheme.ss nondeterministic-stochastic-memoization.ss reduced-gradient.ss stochastic-constraints.ss stochastic-memoization.ss stochastic-montague-grammar.ss stochastic-promises.ss stochastic-recognizer.ss stochastic-scheme.ss ; do
    plt-r6rs --install --force $f
done
